# Generated by Django 4.2.11 on 2024-03-15 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('party_size', models.IntegerField()),
                ('session_length', models.IntegerField(choices=[(2, '2 hours'), (4, '4 hours')])),
                ('start_time', models.CharField(choices=[('10:00', '10 AM'), ('11:00', '11 AM'), ('12:00', '12 PM'), ('13:00', '1 PM'), ('14:00', '2 PM'), ('15:00', '3 PM'), ('16:00', '4 PM'), ('17:00', '5 PM'), ('18:00', '6 PM'), ('19:00', '7 PM'), ('20:00', '8 PM')], max_length=5)),
                ('date', models.DateField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.table')),
            ],
        ),
    ]
