# Generated by Django 4.2.11 on 2024-03-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_party_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='party_size',
            field=models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=2),
        ),
        migrations.AlterField(
            model_name='booking',
            name='session_length',
            field=models.IntegerField(choices=[(2, '2 hours'), (4, '4 hours')], default=2),
        ),
    ]
